In [1]:
### Load Libraries
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
### Load dataset
dataset = pd.read_csv('covid_dataset.csv')
dataset.head(10)

Day  Lab Test  Confirmed case  Death Case
0  2020-April-04       434               9           2
1  2020-April-05       367              18           1
2  2020-April-06       468              35           3
3  2020-April-07       679              41           5
4  2020-April-08       981              54           3
5  2020-April-09       905             112           1
6  2020-April-10      1184              94           6
7  2020-April-11       954              58           3
8  2020-April-12      1340             139           4
9  2020-April-13      1570             182           5

In [3]:
# label_encoder object using
label_encoder = preprocessing.LabelEncoder()
dataset['Day']= label_encoder.fit_transform(dataset['Day']) 
print(dataset.head(100))

    Day  Lab Test  Confirmed case  Death Case
0     0       434               9           2
1     1       367              18           1
2     2       468              35           3
3     3       679              41           5
4     4       981              54           3
..  ...       ...             ...         ...
95   96     15672            3489          46
96   97     15632            3360          41
97   98     13488            2949          37
98   99     11193            2686          30
99  100     11059            2666          47

[100 rows x 4 columns]


In [4]:
dataset.shape

(626, 4)

In [5]:
dataset.describe()

Day      Lab Test  Confirmed case  Death Case
count  626.000000    626.000000      626.000000  626.000000
mean   312.500000  18033.835463     2526.009585   44.798722
std    180.854914   9357.619008     2936.765446   54.528270
min      0.000000    367.000000        9.000000    0.000000
25%    156.250000  12869.500000      657.750000   14.000000
50%    312.500000  15557.000000     1637.000000   30.000000
75%    468.750000  20982.750000     2953.500000   44.000000
max    625.000000  55284.000000    16230.000000  264.000000

In [6]:
### Split Data
X= dataset.drop('Death Case', axis=1)
y= dataset['Death Case']

print('Shape of X =', X.shape)
print('Shape of y =', y.shape)

Shape of X = (626, 3)
Shape of y = (626,)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (500, 3)
Shape of y_train =  (500,)
Shape of X_test =  (126, 3)
Shape of y_test =  (126,)


In [8]:
### Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [9]:
## Linear Regression Model Training
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [10]:
lr.fit(X_train, y_train)

LinearRegression()

In [11]:
lr.coef_

array([ 2.04880305,  3.43219932, 48.44058435])

In [12]:
lr.intercept_

45.07600000000001

In [13]:
## Predict the value
X_test[0, :]

array([ 1.72266509,  1.17136417, -0.41409935])

In [14]:
lr.predict([X_test[0, :]])

array([32.56654222])

In [15]:
lr.predict(X_test)

array([ 32.56654222,  36.80679019,  25.4899513 ,  31.16893779,
        10.5282799 ,  24.9485435 ,  17.98894086, 240.52411889,
       151.62272915,  66.25912629,  36.7127309 ,  11.81337346,
        22.46735431,  30.44697606, 212.63410896,   3.2085731 ,
         8.88346605,  37.64673421,  12.16462155,  70.43262449,
        30.28213319,  35.83818196,  10.06396381,  16.55428257,
        47.03577273,  16.0571018 , 150.01643783,  45.98978623,
        11.85318234,  16.90420875,   2.67172174,  20.37123593,
        64.18246203,  26.38936996,  83.18023084,  47.72222794,
        13.34114856,  19.98809397,  43.94182808,  67.35391417,
         9.21533447,  11.38070417,  39.31979986,  10.10694157,
        98.12741642,  63.89509655,  44.14437211,  17.14279885,
        12.47573772,  35.1023423 ,   9.25087796, 173.25012053,
        67.52600676,  28.21360834,  93.69296954,  38.31131494,
        26.16947981,  10.93975948,  -4.33939842,  35.20978145,
        40.72996345,  24.6315013 ,  22.70274852,  68.37

In [16]:
y_test

542     31
235     39
46      16
215     17
619      3
      ... 
606      2
79      38
284     14
387     97
463    230
Name: Death Case, Length: 126, dtype: int64

In [17]:
lr.score(X_test, y_test)

0.9051714597422712