In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
dataset = pd.read_csv('Mergerd_Dataset.csv')
dataset.head(10)

day  lab_test  confirmed_case  death_case  first_dose  second_dose
0    4/4/2020       434               9           2           0            0
1    5/4/2020       367              18           1           0            0
2    6/4/2020       468              35           3           0            0
3    7/4/2020       679              41           5           0            0
4    8/4/2020       981              54           3           0            0
5    9/4/2020       905             112           1           0            0
6   10/4/2020      1184              94           6           0            0
7   11/4/2020       954              58           3           0            0
8   12/4/2020      1340             139           4           0            0
9  13-04-2020      1570             182           5           0            0

In [3]:
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'Country'. 
dataset['day']= label_encoder.fit_transform(dataset['day']) 
print(dataset.head(100))

    day  lab_test  confirmed_case  death_case  first_dose  second_dose
0   509       434               9           2           0            0
1   530       367              18           1           0            0
2   551       468              35           3           0            0
3   572       679              41           5           0            0
4   593       981              54           3           0            0
..  ...       ...             ...         ...         ...          ...
95  599     15672            3489          46           0            0
96  620     15632            3360          41           0            0
97   35     13488            2949          37           0            0
98   56     11193            2686          30           0            0
99   77     11059            2666          47           0            0

[100 rows x 6 columns]


In [4]:
dataset.shape

(626, 6)

In [5]:
dataset.describe()

day      lab_test  confirmed_case  death_case    first_dose  \
count  626.000000    626.000000      626.000000  626.000000  6.260000e+02   
mean   312.500000  18033.835463     2526.009585   44.798722  1.097140e+05   
std    180.854914   9357.619008     2936.765446   54.528270  3.617676e+05   
min      0.000000    367.000000        9.000000    0.000000  0.000000e+00   
25%    156.250000  12869.500000      657.750000   14.000000  0.000000e+00   
50%    312.500000  15557.000000     1637.000000   30.000000  0.000000e+00   
75%    468.750000  20982.750000     2953.500000   44.000000  9.829925e+04   
max    625.000000  55284.000000    16230.000000  264.000000  6.625123e+06   

        second_dose  
count  6.260000e+02  
mean   7.309854e+04  
std    2.869615e+05  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    1.226475e+04  
max    5.444166e+06

In [6]:
X= dataset.drop('death_case', axis=1)
y= dataset['death_case']

print('Shape of X =', X.shape)
print('Shape of y =', y.shape)

Shape of X = (626, 5)
Shape of y = (626,)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)
 
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (500, 5)
Shape of y_train =  (500,)
Shape of X_test =  (126, 5)
Shape of y_test =  (126,)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
 
lr.fit(X_train, y_train)

LinearRegression()

In [10]:
lr.coef_

array([-0.48195976,  3.22084149, 48.73986805,  3.6692261 ,  0.36513392])

In [11]:
lr.intercept_

45.07600000000001

In [12]:
X_test[0, :]

array([ 0.60582168,  1.17136417, -0.41409935, 24.34522753,  0.17789168])

In [13]:
lr.predict([X_test[0, :]])

array([117.7667473])

In [14]:
lr.predict(X_test)

array([117.7667473 ,  36.39918869,  25.86835825,  30.56377647,
        14.11551411,  25.35061147,  19.26749349, 243.31257407,
       150.63456058,  63.26952416,  35.62979727,   8.83508947,
        23.51345513,  29.16815189, 212.7760831 ,   4.9214525 ,
         9.07850423,  37.33287913,   9.98667625,  67.60199204,
        26.44492043,  35.4945754 ,  11.41563671,  16.10975846,
        48.26085383,  12.80930093, 149.16769889,  48.53829122,
         9.77061359,  15.14162788,   4.85995541,  19.8235408 ,
        63.81509618,  22.14223334,  80.2094246 ,  48.35092403,
        12.30534984,  19.82356945,  45.38141038,  64.67169578,
         6.6268496 ,  12.16989098,  40.61071052,  10.0916502 ,
        97.40984555,  64.13935561,  46.04918908,  18.04835536,
        13.19316732,  36.78176263,   8.00857914, 170.49759551,
        64.67649868,  28.08910386,  90.40485212,  34.96324526,
        26.92764113,   8.22242193,  -2.97562403,  32.81302677,
        41.8059407 ,  25.16208445,  18.81421172,  66.44

In [15]:
y_test

542     31
235     39
46      16
215     17
619      3
      ... 
606      2
79      38
284     14
387     97
463    230
Name: death_case, Length: 126, dtype: int64

In [16]:
lr.score(X_test, y_test)

0.8770111380185591